# For Github User
# github_username: "slack_member_id"
# please_replace_me_11: U01G30S9LHW
# please_replace_me_4: U011F5DRG2V

Naoki0722: "U02GS3WCB8U"
# github_username_B: "slack_member_id_B"
# github_username_C: "slack_member_id_C"
# abeyuya: "XXXXXXXXX"

# For Github Team
# github_teamname: "slack_member_id"
# github_teamname_A: "slack_member_id_D"
